name: index
description: "Index - Modern VOD Streaming App by Voxin"
version: 2.1.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  
  # Core dependencies
  http: ^0.13.6
  shared_preferences: ^2.2.0
  package_info_plus: ^4.2.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  
  # UI dependencies
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  flutter_settings_ui: ^2.0.1
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.4
  smooth_page_indicator: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  swipeable_page_route: ^0.3.0
  
  # Video & Media
  video_player: ^2.7.0
  audio_video_progress_bar: ^1.0.1
  subtitle_wrapper_package: ^2.1.1
  wakelock_plus: ^1.1.1
  
  # Firebase
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  firebase_remote_config: ^4.2.4
  cloud_firestore: ^4.8.4
  
  # Utilities
  archive: ^3.3.7
  internet_connection_checker_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - fonts/
