// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDummy_Web_Key_Replace_With_Real_Key',
    appId: '1:123456789:web:dummy_app_id',
    messagingSenderId: '123456789',
    projectId: 'index-voxin',
    authDomain: 'index-voxin.firebaseapp.com',
    storageBucket: 'index-voxin.appspot.com',
    measurementId: 'G-DUMMY_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyDummy_Android_Key_Replace_With_Real_Key',
    appId: '1:123456789:android:dummy_app_id',
    messagingSenderId: '123456789',
    projectId: 'index-voxin',
    storageBucket: 'index-voxin.appspot.com',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyDummy_iOS_Key_Replace_With_Real_Key',
    appId: '1:123456789:ios:dummy_app_id',
    messagingSenderId: '123456789',
    projectId: 'index-voxin',
    storageBucket: 'index-voxin.appspot.com',
    iosBundleId: 'com.voxin.index',
  );

  static const FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyDummy_macOS_Key_Replace_With_Real_Key',
    appId: '1:123456789:macos:dummy_app_id',
    messagingSenderId: '123456789',
    projectId: 'index-voxin',
    storageBucket: 'index-voxin.appspot.com',
    iosBundleId: 'com.voxin.index',
  );

  static const FirebaseOptions windows = const FirebaseOptions(
    apiKey: 'AIzaSyDummy_Windows_Key_Replace_With_Real_Key',
    appId: '1:123456789:windows:dummy_app_id',
    messagingSenderId: '123456789',
    projectId: 'index-voxin',
    storageBucket: 'index-voxin.appspot.com',
  );
}